version: '3'
services:
  wiremock:
    image: wiremock/wiremock:2.35.0
    container_name: wiremock
    ports:
      - "8081:8080"
    volumes:
      - ./src/test/resources/mappings:/home/wiremock/mappings
      - ./src/test/resources/recordings:/home/wiremock/recordings
    environment:
      - JAVA_OPTS=-Dcom.sun.net.ssl.checkRevocation=false
    restart: always
